# FONCIER+ v3.5.2 — nginx.prod.conf
user nginx;
worker_processes auto;
events { worker_connections 1024; }

http {
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    gzip on;
    gzip_comp_level 6;
    gzip_types text/css application/javascript application/json text/plain;

    limit_req_zone $binary_remote_addr zone=api_zone:10m rate=60r/m;
    limit_req_zone $binary_remote_addr zone=login_zone:10m rate=5r/m;

    upstream backend { server backend:8000 keepalive 32; }
    upstream frontend { server frontend:80 keepalive 16; }

    server {
        listen 80;
        server_name foncier.gov.ne;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name foncier.gov.ne;

        ssl_certificate     /etc/nginx/ssl/foncier.gov.ne.crt;
        ssl_certificate_key /etc/nginx/ssl/foncier.gov.ne.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_session_tickets off;

        add_header Strict-Transport-Security "max-age=63072000" always;
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;

        location /v1/auth/login {
            limit_req zone=login_zone burst=3 nodelay;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/ {
            limit_req zone=api_zone burst=20 nodelay;
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 60s;
        }

        location /verification {
            proxy_pass http://backend;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
        }
    }
}
